export const CHANGE_MODE = "CHANGE_MODE"

export const GET_RANDOM_PHOTO_BEGIN = "GET_RANDOM_PHOTO_BEGIN"
export const GET_RANDOM_PHOTO_SUCCESS = "GET_RANDOM_PHOTO_SUCCESS"
export const GET_RANDOM_PHOTO_ERROR = "GET_RANDOM_PHOTO_ERROR"

export const GET_USER_INFO_BEGIN = "GET_USER_INFO_BEGIN"
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS"
export const GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR"

export const GET_USER_PHOTOS_BEGIN = "GET_USER_PHOTOS_BEGIN"
export const GET_USER_PHOTOS_SUCCESS = "GET_USER_PHOTOS_SUCCESS"
export const GET_USER_PHOTOS_ERROR = "GET_USER_PHOTOS_ERROR"