export const CHANGE_MODE = "CHANGE_MODE"

export const GET_RANDOM_PHOTO_BEGIN = "GET_RANDOM_PHOTO_BEGIN"
export const GET_RANDOM_PHOTO_SUCCESS = "GET_RANDOM_PHOTO_SUCCESS"
export const GET_RANDOM_PHOTO_ERROR = "GET_RANDOM_PHOTO_ERROR"